(package "vs-light-theme"
         "1.0"
         "Visual Studio IDE light theme")

(website-url "https://github.com/emacs-vs/vs-light-theme")
(keywords "")

(package-file "vs-light-theme.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source "melpa")

(depends-on "emacs" "24.1")

(development
 (depends-on "ert-runner"))

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
